[package]
name = "zarr-datafusion-search"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "58.0.0"
arrow-array = "58.0.0"
arrow-schema = "58.0.0"
async-trait = "0.1.89"
datafusion = "53.0"
futures = "0.3.31"
geo-index = "0.2"
geo-traits = "0.3"
geodatafusion = "0.4"
wkt = { version = "0.14", default-features = false }
geoarrow-schema = "0.8.0"
icechunk = "0.3.16"
object_store = "0.12.4"
thiserror = "2"
tokio = { version = "1.48", features = ["rt"] }
zarrs = { version = "0.23.10", features = ["async", "chrono"] }
zarrs_filesystem = "0.3.9"
zarrs_metadata = "0.7.4"
zarrs_icechunk = "0.4.2"
zarrs_object_store = "0.5.0"
zarrs_storage = { version = "0.4.3", features = ["async"] }
stac = { version = "0.17.0", features = ["geoarrow", "async"] }
stac-io = "0.2.8"
tracing = "0.1"

[dev-dependencies]
bytesize = "1"
chrono = "0.4.44"
criterion = { version = "0.5.1", features = ["async_tokio"] }
dhat = "0.3"
geo = "0.31"
geo-index = "0.2"
geoarrow-array = "0.8.0"
rand = "0.8"
tempfile = "3"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
wkb = "0.9"

[[bench]]
name = "datetime_local"
harness = false
test = false

[[bench]]
name = "datetime_s3"
harness = false
test = false

[[bench]]
name = "bbox_local"
harness = false
test = false

[[bench]]
name = "bbox_s3"
harness = false
test = false

[[bench]]
name = "bbox_columns_local"
harness = false
test = false

[[bench]]
name = "bbox_columns_s3"
harness = false
test = false

[[bench]]
name = "bbox_zarrs_raw"
harness = false
test = false

[[example]]
name = "generate_s3_store"
path = "examples/generate_s3_store.rs"
