[package]
name = "zarr-datafusion-search"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "57.0.0"
arrow-array = "57.0.0"
arrow-schema = "57.0.0"
async-trait = "0.1.89"
datafusion = "52.0"
futures = "0.3.31"
geodatafusion = "0.3"
geoarrow-schema = "0.7.0"
icechunk = "0.3.16"
object_store = "0.12.4"
thiserror = "2"
tokio = "1.48"
zarrs = { version = "0.22.5", features = ["async", "chrono"] }
zarrs_filesystem = "0.3.3"
zarrs_metadata = "0.6.2"
zarrs_icechunk = "0.4.1"
zarrs_object_store = "0.5.0"
zarrs_storage = { version = "0.4.0", features = ["async"] }

[dev-dependencies]
chrono = "0.4.44"
criterion = "0.5.1"
geo = "0.31"
geoarrow-array = "0.7.0"
rand = "0.8"
tempfile = "3"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
wkb = "0.9"

[[bench]]
name = "datetime_filter"
harness = false
