name: Python

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: "clippy --all"
        run: cargo clippy --all --all-features --tests -- -D warnings

      - name: "cargo check"
        run: cargo check --all --all-features

      - name: uv sync
        working-directory: python
        run: uv sync --no-install-package zarr-datafusion-search

      - name: "Maturin develop"
        run: |
          uv run --no-project maturin develop --uv

      - name: Run pytest
        working-directory: python
        run: uv run --no-project pytest
